default_platform(:ios)

platform :ios do

  desc "Build and upload to App Store Connect"
  lane :deploy do
    setup_ci

    # Install certificate and provisioning profile from environment
    import_certificate(
      certificate_path: "signing/cert.p12",
      certificate_password: ENV["APPLE_SIGNING_CERTIFICATE_PASSWORD"],
      keychain_name: "build.keychain",
      keychain_password: "temp1234"
    )

    install_provisioning_profile(
      path: "signing/profile.mobileprovision"
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/App/App.xcodeproj",
      code_sign_identity: "iPhone Distribution",
      profile_name: "gustilk AppStore"
    )

    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "gustilk.ipa"
    )

    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"]
    )

    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      force: true
    )
  end

end
